// <auto-generated />
using AlbumCollection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumCollection.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20190308201947_JoinSongsToAlbum")]
    partial class JoinSongsToAlbum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumCollection.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new { Id = 1, Artist = "Frank Ocean", Title = "Nostalgia, Ultra" },
                        new { Id = 2, Artist = "Frank Ocean", Title = "Channel Orange" },
                        new { Id = 3, Artist = "Frank Ocean", Title = "Blonde" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new { Id = 1, AlbumId = 1, Title = "Strawberry Swing" },
                        new { Id = 2, AlbumId = 1, Title = "Novacane" },
                        new { Id = 3, AlbumId = 1, Title = "We All Try" },
                        new { Id = 4, AlbumId = 1, Title = "Songs 4 Women" },
                        new { Id = 5, AlbumId = 1, Title = "Lovecrimes" },
                        new { Id = 6, AlbumId = 1, Title = "There Will Be Tears" },
                        new { Id = 7, AlbumId = 1, Title = "Swim Good" },
                        new { Id = 8, AlbumId = 1, Title = "Dust" },
                        new { Id = 9, AlbumId = 1, Title = "American Wedding" },
                        new { Id = 10, AlbumId = 1, Title = "Nature Feels" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.HasOne("AlbumCollection.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
